name: Test and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.0
      with:
        node-version: 15.x
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Test
      run: npm run test:cov

  integration-test:
    needs: test-coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run integration tests
        run: docker-compose up --exit-code-from restapi


  deploy:
    needs: integration-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        name: Deploy to Heroku
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "slack-boto"
          heroku_email: ${{secrets.DEPLOY_EMAIL}}
          usedocker: true
          docker_build_args: |
            NODE_ENV
        env:
          NODE_ENV: production